name: ppscgym
description: PPSC GYM record maintaining application
version: 1.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  sqflite: ^2.0.0+3
  path: ^1.8.0
  intl: ^0.17.0
  path_provider: ^2.0.2
  url_launcher: ^6.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
